# Generated by Django 4.2.1 on 2023-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressStandardization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=60)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
